[fix] upgrade port settings
YunoHost-Apps/grafana_ynh pull request #8
Opened 2017-05-15 20:54 UTC by nemsia

2017-05-16 17:51 UTC, JimboJoe requested changes
Could you please also add `systemctl restart grafana-server` on line 34? That's not strictly mandatory, but that seems logical and it prevents package_check from failing.
The idea is to maintain level 7 for this app ;-)

2017-05-16 17:51 UTC, JimboJoe commented on scripts/upgrade
> +if [[ "$port" = "" ]]; then
`if [ -z "$port"] ; then` would be much better

2017-05-17 15:01 UTC, nemsia commented on scripts/upgrade
> +if [[ "$port" = "" ]]; then
Fix on https://github.com/YunoHost-Apps/grafana_ynh/pull/8/commits/7b610bf02e0fdc2116733ed907602cc38056a20f

2017-05-17 15:06 UTC, nemsia commented
* Add restart https://github.com/YunoHost-Apps/grafana_ynh/pull/8/commits/4f453504891b30a2bf0ad8dc9dd71963b451e10c
* Better port check https://github.com/YunoHost-Apps/grafana_ynh/pull/8/commits/7b610bf02e0fdc2116733ed907602cc38056a20f
Tested on my own test server.

2017-05-18 18:45 UTC, JimboJoe approved these changes
Thanks again!

2017-05-18 18:45 UTC, merged

2017-05-18 18:46 UTC, JimboJoe commented
@nemsia Thanks! Don't forget next time to work in a branch directly in the Yunohost-Apps repository; I will then be able to participate to the PR ;-)